done view list of article
jd4545/News-Frontend pull request #1
Opened 2022-03-07 16:51 UTC by jd4545

2022-03-07 16:54 UTC, popatre requested changes
Just have a look at those two small things, then merge.

2022-03-07 16:54 UTC, popatre commented on src/App.js
> +      <DisplayArticles />
You might find you have to put this in a home route, moving forward. Cross that bridge when you come to it

2022-03-07 16:54 UTC, popatre commented on src/components/display-articles.jsx
> +    // ARTICLES on HOME page
- [ ] Is loading - for user feedback during the api request
- [ ] Error handling - incase the request has a problem - little error message/component that displays instead

2022-03-08 11:11 UTC, jd4545 commented
Added isLoading for articles page, and error for incorrect routes

2022-03-08 11:11 UTC, merged